# Generated by Django 3.1.3 on 2020-12-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollegeApp', '0003_staff_usermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='leavestatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
