# Generated by Django 3.1.3 on 2020-12-26 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CollegeApp', '0004_leavestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=120)),
                ('message', models.TextField(max_length=420)),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='CollegeApp.leavestatus')),
                ('std_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollegeApp.usermodel')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollegeApp.staff')),
            ],
        ),
    ]
