# Generated by Django 3.1.3 on 2020-12-26 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CollegeApp', '0005_leave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='teacher',
        ),
    ]
