# Generated by Django 3.1.3 on 2020-12-27 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollegeApp', '0006_remove_leave_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='std_id',
            field=models.IntegerField(),
        ),
    ]
